# Generated by Django 4.2.2 on 2023-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0010_subscription_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="status",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment_id",
            field=models.CharField(
                blank=True, default="MANUAL", max_length=255, null=True
            ),
        ),
    ]
