# Generated by Django 4.2.2 on 2023-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0011_remove_subscription_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
